export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "主键",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "是否签订责任书(1:是，0:不是)",
      "prop": "responsibilityFlag"
    },	  {
      "type": "input",
      "label": "企业名称",
      "prop": "enterpriseName"
    },	  {
      "type": "input",
      "label": "统一社会信用代码",
      "prop": "socialCreditNumber"
    },	  {
      "type": "input",
      "label": "经营范围",
      "prop": "businessScope"
    },	  {
      "type": "input",
      "label": "地址",
      "prop": "address"
    },	  {
      "type": "input",
      "label": "所属街道:街道选择 澳头/西区/霞涌",
      "prop": "belongStreet"
    },	  {
      "type": "input",
      "label": "所属社区",
      "prop": "belongCommunity"
    },	  {
      "type": "input",
      "label": "所属网格(需求待确定",
      "prop": "belongGrid"
    },	  {
      "type": "input",
      "label": "责任人",
      "prop": "owner"
    },	  {
      "type": "input",
      "label": "责任人身份证号",
      "prop": "ownerIdentityNumber"
    },	  {
      "type": "input",
      "label": "责任人联系电话",
      "prop": "ownerPhone"
    },	  {
      "type": "input",
      "label": "法定代表人电话",
      "prop": "legalRepresentativePhone"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    },	  {
      "type": "input",
      "label": "二维码地址",
      "prop": "qrUrl"
    },	  {
      "type": "input",
      "label": "二维码编号",
      "prop": "qrNumber"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "逻辑删除标志(1:删除，0：未删除",
      "prop": "deleteFlag"
    }  ]
}
